/* JavaScript Document*/
app.objs.routeTable={
	/*公共部分***********************************************************************************/
	/*首页*/
	"index":{
			type:0,
			fn:function(data){
			/*获取宣传*/
			app.apis.getpromotion(data,function(promotion){
				/*获取公告*/
				app.apis.getannouncement(data,function(announcement){
					/*获取商品*/
					app.apis.getProduct(data,function(product){
						
						/*出页面*/
						console.log(promotion);
						console.log(announcement);
						console.log(product);
						var promoArry=[];
						$.each(promotion,function(i,n){
							if(n.group=="index"){
								promoArry.push(n);
								}
							})
						app.objs.indexV.data = {
							promotion : promoArry,
							announcement : announcement,
							product : product
							}
						app.objs.indexV.render();

						});
					});
				});
			}
		},
	/*众筹模式*/
	"mode":{
			type:0,
			fn:function(data){
			/*获取宣传*/
			app.apis.getpromotion(data,function(promotion){
				/*出页面*/
				app.objs.modeV.data = promotion.mode
				app.objs.modeV.render();
				});
			}
		},
	/*我要众筹*/
	"product":{
				type:0,
				fn:function(data){
				/*获取商品*/
						app.apis.getProduct(data,function(Product){
							/*出页面*/
							var fenzu={
								noStart:[],
								on:[],
								end:[]
								}
								if(Product){
									$.each(Product,function(i,n){
									if(n.copy<=n.payedCount||n.money<=n.payed){
										fenzu.end.push(n)
										}else if(n.stratTime<new Date().getTime()){
											fenzu.on.push(n)
											}else{
												fenzu.noStart.push(n)
												}
									})
									}
								
							app.objs.productV.data = fenzu;
							app.objs.productV.render();
						});
				}
		},
	/*众筹步聚*/	
	"procedure":{
				type:0,
				fn:function(data){
				/*获取宣传*/
				app.apis.getpromotion(data,function(promotion){
					/*出页面*/
					var promoArry=[];
						$.each(promotion,function(i,n){
							if(n.group=="procedure"){
								promoArry.push(n);
								}
							})
					app.objs.procedureV.data = promoArry
					app.objs.procedureV.render();
					});
				}
		},
	/*常见问题*/
	"FAQS":{
			type:0,
			fn:function(data){
			/*获取宣传*/
			app.apis.getpromotion(data,function(promotion){
				/*出页面*/
				var promoArry=[];
						$.each(promotion,function(i,n){
							if(n.group=="FAQS"){
								promoArry.push(n);
								}
							})
				app.objs.FAQSV.data=promoArry
			app.objs.FAQSV.render();
				});
			}
		},
	/*关于我们*/
	"about":{
			type:0,
			fn:function(data){
			/*获取宣传*/
			app.apis.getpromotion(data,function(promotion){
				/*获取公告*/
				app.apis.getannouncement(data,function(announcement){
					/*获取招聘*/
					app.apis.getrecruit(data,function(recruit){
						/*获取公司信息*/
						app.apis.getcompany(data,function(company){
							/*出页面*/
							var promoArry=[];
							var promoArryI=[];
						$.each(promotion,function(i,n){
							if(n.group=="team"){
								promoArry.push(n);
								}
							if(n.group=="idea"){
								promoArryI.push(n);
								}
							})
						app.objs.aboutV.data={
							team:promoArry,
							idea:promoArryI,
							announcement:announcement,
							recruit:recruit,
							company:company
						}
						app.objs.aboutV.render();
						},function(){alert("获取公司信息失败")})
						});
					});
				});
			}
		},
	/*产品详情*/	
	"productDetail":{
					type:0,
					fn:function(data){
					/*出页面*/
					app.apis.getProduct(null,function(dataA){
						var dataA=_.indexBy(dataA,"id")
						if(dataA[data.id]){
							app.objs.productDetailV.data=dataA[data.id];
							app.objs.productDetailV.render();
							}
						},function(){
							alert("获取商品出错")
							})
					
					}
		},
	/*购买*/
	"buy":{
		type:0,
					fn:function(data){
					/*出页面*/
					app.apis.getProduct(null,function(dataA){
						var dataA=_.indexBy(dataA,"id")
						if(dataA[data.id]){
							app.objs.buyV.data={
								id:app.fns.uuid(),
								productId:data.id,
								userId:app.objs.user.get().id,
								title:dataA[data.id].title,
								subhead:dataA[data.id].subhead,
								count:Number(data.count),
								startTime:new Date().getTime(),
								buyPrice:dataA[data.id].UnitPrice,
								endTime:null,
								sellPrice:null,
								}
								app.objs.buyV.render();
							}
						},function(){
							alert("获取商品出错")
							})
					
					}
		},
	/*卖出*/
	"sell":{
		type:0,
					fn:function(data){
					/*出页面*/
					
					function getProduct(){
						app.apis.getProduct(null,function(dataA){
						var dataA=_.indexBy(dataA,"id")
						if(dataA[app.objs.sellV.data.productId]){
								app.objs.sellV.data.sellPrice=dataA[app.objs.sellV.data.productId].UnitPrice;
								app.objs.sellV.data.title=dataA[app.objs.sellV.data.productId].title;
								app.objs.sellV.data.subhead=dataA[app.objs.sellV.data.productId].subhead;
								app.objs.sellV.render();
							}
						},function(){
							alert("获取商品出错")
							})
						}
					app.apis.getdealList(null,function(dataA){
						var dataA=_.indexBy(dataA,"id")
						if(dataA[data.id]){
							app.objs.sellV.data=dataA[data.id];
							app.objs.sellV.data.endTime=new Date().getTime();
							getProduct()
							}
						},function(){
						alert("获取交易信息失败")
						})
					
					}
		},
		/*卖出*/
	"change":{
		type:0,
					fn:function(data){
					/*出页面*/
					
					function getProduct(){
						app.apis.getProduct(null,function(dataA){
						var dataA=_.indexBy(dataA,"id")
						if(dataA[app.objs.changeV.data.productId]){
								app.objs.changeV.data.sellPrice=dataA[app.objs.changeV.data.productId].UnitPrice;
								app.objs.changeV.data.title=dataA[app.objs.changeV.data.productId].title;
								app.objs.changeV.data.subhead=dataA[app.objs.changeV.data.productId].subhead;
								app.objs.changeV.data.change=dataA[app.objs.changeV.data.productId].change;
								app.objs.changeV.render();
							}
						},function(){
							alert("获取商品出错")
							})
						}
					app.apis.getdealList(null,function(dataA){
						var dataA=_.indexBy(dataA,"id")
						if(dataA[data.id]){
							app.objs.changeV.data=dataA[data.id]
							getProduct()
							}
						},function(){
						alert("获取交易信息失败")
						})
					
					}
		},
	/*公告详情*/
	"announcementDetail":{
					type:0,
					fn:function(data){
					/*出页面*/
					app.objs.announcementDetailV.render();
					}
		},
	/*登录*/
	"login":{
			type:0,
			fn:function(data){
			/*出页面*/
			app.objs.loginV.render();
		//onload = function () {

		}
		//	}
		},
	/*注册*/
	"register":{
				type:0,
				fn:function(data){
				/*出页面*/
				app.objs.registerV.render();
				}
		},
	/*用户空间***********************************************************************************/
	/*帐户*/
	"account":{
				type:1,
				fn:function(data){
					app.objs.accountV.el=".mb_right";
					app.objs.accountV.data=app.objs.user.get();
					function getProduct(){
						app.apis.getProduct(null,function(data){
						var data=_.indexBy(data,"id");
						app.objs.accountV.data.product=data;
						app.objs.accountV.render();
						})
						}
					function getDeal(){
						app.apis.getdealList(null,function(data){
							app.objs.accountV.data.deal=data
							getProduct();
							},function(){
							alert("获取交易信息失败")
							})
						}
					function getbind(){
						app.apis.getBind(null,function(data){
						app.objs.accountV.data.bind=data;
						/*出页面*/
					getDeal()
						},function(){
							alert("获取绑定信息失败")
							})
						}
					app.apis.getSafeQusetion(null,function(){
						app.objs.accountV.data.saveQuestion=true;
						getbind()
						},function(){
							app.objs.accountV.data.saveQuestion=false;
							getbind()
							})
				}
		},
	/*充值*/
	"recharge":{
				type:1,
				fn:function(data){
				/*出页面*/
				app.objs.rechargeV.render();
				}
		},
	/*提现*/
	"paid":{
			type:1,
			fn:function(data){
			/*获取帐户信息*/
			app.apis.getAccount(data,function(Account){
				/*出页面*/
				app.objs.paidV.render();
				});
			}
		},
	/*银行卡*/
	"card":{
		type:1,
		fn:function(data){
		/*获取帐户信息*/
		app.apis.getAccount(data,function(Account){
			/*出页面*/
		app.objs.cardV.render();
		});
		}
		},
	/*资金记录*/
	"capitalDetail":{
					type:1,
					fn:function(data){
					/*获取帐户信息*/
					function getDeal(product){
						app.apis.getdealList(data,function(dealList){
						/*出页面*/
						if(dealList){
						$.each(dealList,function(i,deal){
							deal.title=product[deal.productId].title;
							deal.subhead=product[deal.productId].subhead;
							deal.minUnit=product[deal.productId].minUnit;
							})
						}
					app.objs.capitalDetailV.el=".mb_right";
					app.objs.capitalDetailV.data=dealList;
					app.objs.capitalDetailV.render();
					});
						}
					
					app.apis.getProduct(null,function(product){
						product=_.indexBy(product,"id");
						getDeal(product);
						},function(){
						alert("获取商品信息失败")
						});
					}
		},
	/*红包记录*/
	"redPacketDetail":{
						type:1,
						fn:function(data){
						/*获取红包*/
						app.apis.redPacketDetail(data,function(redPacket){
							app.objs.redPacketDetailV.el=".mb_right";
							app.objs.redPacketDetailV.data=redPacket;
							/*出页面*/
						app.objs.redPacketDetailV.render();
							});
						}
		},
	/*安全问题*/
	"safeQusetion":{
					type:1,
					fn:function(data){
					/*获取安全问题*/
					app.apis.getSafeQusetion(data,function(SafeQusetion){
						/*出页面*/
						app.objs.safeQusetionV.el=".mb_right";
						app.objs.safeQusetionV.data=SafeQusetion;
						app.objs.safeQusetionV.render();
						})
					}
		},
	/*邮箱验证*/
	"emailVerify":{
					type:1,
					fn:function(data){
					/*出页面*/
					app.objs.emailVerifyV.el=".mb_right";
					app.objs.emailVerifyV.data=app.objs.user.get();
					app.apis.getBind(null,function(bind){
						app.objs.emailVerifyV.data.bind=bind;
						app.objs.emailVerifyV.render();
						},function(){
						alert("绑定信息获取失败")
						})
					
					}
		},
	/*修改手机*/
	"setPhone":{
				type:1,
				fn:function(data){
				/*出页面*/
				app.objs.setPhoneV.el=".mb_right";
				app.objs.setPhoneV.data=app.objs.user.get();
				app.apis.getBind(null,function(bind){
						app.objs.setPhoneV.data.bind=bind;
						app.objs.setPhoneV.render();
						},function(){
						alert("绑定信息获取失败")
						})
			
				}
		},
	/*修改资料*/
	"setDetail":{
				type:1,
				fn:function(data){
				/*出页面*/
				app.objs.setDetailV.el=".mb_right";
				app.objs.setDetailV.data=app.objs.user.get();
				app.objs.setDetailV.render();
				}
		},
	/*修改密码*/
	"setPassWord":{
					type:1,
					fn:function(data){
					/*出页面*/
					app.objs.setPassWordV.el=".mb_right";
					app.objs.setPassWordV.render();
					}
		},
	/*后台管理***********************************************************************************************/
	/*管理员管理*/
	"adminManage":{
					type:2,
					fn:function(data){
					/*获取管理员*/
					app.apis.getAdmin(data,function(Admin){
						/*出页面*/
					app.objs.adminManageV.el=".mb_right";
					app.objs.adminManageV.data=Admin;
					app.objs.adminManageV.render();
						});
					}
		},
	/*公告管理*/
	"announcementManage":{
						type:2,
						fn:function(data){
						/*获取公告*/
						app.apis.getannouncement(data,function(announcement){
							/*出页面*/
						app.objs.announcementManageV.el=".mb_right";
						app.objs.announcementManageV.data=announcement
						app.objs.announcementManageV.render()
							})
						}
		},
	/*客户管理*/
	"clientManage":{
					type:2,
					fn:function(data){
					/*获取客户资料*/
					app.apis.getClient(data,function(Client){
						/*出页面*/
						app.objs.clientManageV.el=".mb_right";
						app.objs.clientManageV.data=Client;
						app.objs.clientManageV.render();
						})
					}
		},
	/*客户详情*/
	"clientDetail":{
				type:2,
				fn:function(data){
				/*出页面*/
				app.objs.clientDetailV.el=".mb_right";
				app.objs.clientDetailV.render();
				}
		},
	/*商品管理*/
	"procedureManage":{
					type:2,
					fn:function(data){
					/*获取商品信息*/
					app.apis.getProduct(data,function(Product){
						/*出页面*/
					app.objs.procedureManageV.el=".mb_right";
					app.objs.procedureManageV.data=Product;
					app.objs.procedureManageV.render();
						})
					}
		},
	/*招聘管理*/
	"recruitManage":{
		type:2,
		fn:function(data){
		/*获取招聘信息*/
		app.apis.getrecruit(data,function(recruit){
			/*出页面*/
			app.objs.recruitManageV.el=".mb_right";
			app.objs.recruitManageV.data=recruit;
			app.objs.recruitManageV.type=0;
			app.objs.recruitManageV.render();
			})
		}
	},
	/*公司资料管理*/
	"companyManage":{
		type:2,
		fn:function(data){
		/*获取公司资料*/
		app.apis.getcompany(data,function(company){
			/*出页面*/
			app.objs.companyManageV.el=".mb_right";
			app.objs.companyManageV.data=company;
			app.objs.recruitManageV.type=1;
			app.objs.companyManageV.render();
			})	
		}
		},
	/*宣传管理*/
	"promotionManage":{
		type:2,
		fn:function(data){
		/*获取宣传信息*/
		app.apis.getpromotion(data,function(promotion){
			/*出页面*/
			app.objs.promotionManageV.el=".mb_right";
			app.objs.promotionManageV.data=promotion;
			app.objs.promotionManageV.render();
			})
		}
		},
	/*红包管理*/
	"redPacketManage":{
				type:2,
				fn:function(data){
				/*获取红包信息*/
				app.apis.getRedPacket(data,function(redPacket){
					/*出页面*/
					app.objs.redPacketManageV.el=".mb_right";
					app.objs.redPacketManageV.data=redPacket;
					app.objs.redPacketManageV.render();
					})
				}
		},
	/*配置管理*/
	"configManage":{
		type:2,
		fn:function(data){
			/*获取配置信息*/
			app.apis.getConfig(data,function(config){
					/*出页面*/
					app.objs.configManageV.el=".mb_right";
					app.objs.configManageV.data=config;
					app.objs.configManageV.render();
					})
			}
		},	
	/*分享*/
	"share":{
		type:1,
		fn:function(data){
			/*获取配置信息*/
			app.apis.getConfig(data,function(config){
					/*出页面*/
					app.objs.shareV.el=".mb_right";
					app.objs.shareV.data=config;
					app.objs.shareV.render();
					})
			}
		}	
	}
