/* JavaScript Document*/
app.objs.routeTable={
	/*公共部分***********************************************************************************/
	/*首页*/
	"index":{
			type:0,
			fn:function(data){
			/*获取宣传*/
			app.apis.getpromotion(data,function(promotion){
				/*获取公告*/
				app.apis.getannouncement(data,function(announcement){
					/*获取商品*/
					app.apis.getProduct(data,function(product){
						/*出页面*/
						app.objs.indexV.data = {
							promotion : promotion.index,
							announcement : announcement,
							product : product
							}
						app.objs.indexV.render();
						});
					});
				});
			}
		},
	/*众筹模式*/
	"mode":{
			type:0,
			fn:function(data){
			/*获取宣传*/
			app.apis.getpromotion(data,function(promotion){
				/*出页面*/
				app.objs.modeV.data = promotion.mode
				app.objs.modeV.render();
				});
			}
		},
	/*我要众筹*/
	"product":{
				type:0,
				fn:function(data){
				/*获取商品*/
						app.apis.getProduct(data,function(Product){
							/*出页面*/
							app.objs.productV.data = Product;
							app.objs.productV.render();
						});
				}
		},
	/*众筹步聚*/	
	"procedure":{
				type:0,
				fn:function(data){
				/*获取宣传*/
				app.apis.getpromotion(data,function(promotion){
					/*出页面*/
					app.objs.procedureV.data = promotion.procedure
					app.objs.procedureV.render();
					});
				}
		},
	/*常见问题*/
	"FAQS":{
			type:0,
			fn:function(data){
			/*获取宣传*/
			app.apis.getpromotion(data,function(promotion){
				/*出页面*/
				app.objs.FAQSV.data=promotion.FAQS
			app.objs.FAQSV.render();
				});
			}
		},
	/*关于我们*/
	"about":{
			type:0,
			fn:function(data){
			/*获取宣传*/
			app.apis.getpromotion(data,function(promotion){
				/*获取公告*/
				app.apis.getannouncement(data,function(announcement){
					/*获取招聘*/
					app.apis.getrecruit(data,function(recruit){
						/*获取公司信息*/
						app.apis.getcompany(data,function(company){
							/*出页面*/
						app.objs.aboutV.data={
							team:promotion.team,
							idea:promotion.idea,
							announcement:announcement,
							recruit:recruit,
							company:company
						}
						app.objs.aboutV.render();
						},function(){alert("获取公司信息失败")})
						});
					});
				});
			}
		},
	/*产品详情*/	
	"productDetail":{
					type:0,
					fn:function(data){
					/*出页面*/
					app.objs.productDetailV.render();
					}
		},
	/*公告详情*/
	"announcementDetail":{
					type:0,
					fn:function(data){
					/*出页面*/
					app.objs.announcementDetailV.render();
					}
		},
	/*登录*/
	"login":{
			type:0,
			fn:function(data){
			/*出页面*/
			app.objs.loginV.render();
			}
		},
	/*注册*/
	"register":{
				type:0,
				fn:function(data){
				/*出页面*/
				app.objs.registerV.render();
				}
		},
	/*用户空间***********************************************************************************/
	/*帐户*/
	"account":{
				type:1,
				fn:function(data){
				/*获取帐户信息*/
				app.apis.getAccount(data,function(Account){
					/*出页面*/
					app.objs.accountV.render();
					});
				}
		},
	/*充值*/
	"recharge":{
				type:1,
				fn:function(data){
				/*出页面*/
				app.objs.rechargeV.render();
				}
		},
	/*提现*/
	"paid":{
			type:1,
			fn:function(data){
			/*获取帐户信息*/
			app.apis.getAccount(data,function(Account){
				/*出页面*/
				app.objs.paidV.render();
				});
			}
		},
	/*银行卡*/
	"card":{
		type:1,
		fn:function(data){
		/*获取帐户信息*/
		app.apis.getAccount(data,function(Account){
			/*出页面*/
		app.objs.cardV.render();
		});
		}
		},
	/*资金记录*/
	"capitalDetail":{
					type:1,
					fn:function(data){
					/*获取帐户信息*/
					app.apis.getAccount(data,function(Account){
						/*出页面*/
					app.objs.capitalDetailV.render();
					});
					}
		},
	/*红包记录*/
	"redPacketDetail":{
						type:1,
						fn:function(data){
						/*获取红包*/
						app.apis.redPacketDetail(data,function(redPacket){
							app.objs.redPacketDetailV.data=redPacket;
							/*出页面*/
						app.objs.redPacketDetailV.render();
							});
						}
		},
	/*安全问题*/
	"safeQusetion":{
					type:1,
					fn:function(data){
					/*获取安全问题*/
					app.apis.getSafeQusetion(data,function(SafeQusetion){
						/*出页面*/
						app.objs.safeQusetionV.render();
						})
					}
		},
	/*邮箱验证*/
	"emailVerify":{
					type:1,
					fn:function(data){
					/*出页面*/
					app.objs.emailVerifyV.data=app.objs.user.set();
					app.objs.emailVerifyV.render();
					}
		},
	/*修改手机*/
	"setPhone":{
				type:1,
				fn:function(data){
				/*出页面*/
				app.objs.setPhoneV.data=app.objs.user.set();
				app.objs.setPhoneV.render();
				}
		},
	/*修改资料*/
	"setDetail":{
				type:1,
				fn:function(data){
				/*出页面*/
				app.objs.setDetailV.data=app.objs.user.set();
				app.objs.setDetailV.render();
				}
		},
	/*修改密码*/
	"setPassWord":{
					type:1,
					fn:function(data){
					/*出页面*/
					app.objs.setPassWord.render();
					}
		},
	/*后台管理***********************************************************************************************/
	/*管理员管理*/
	"adminManage":{
					type:2,
					fn:function(data){
					/*获取管理员*/
					app.apis.getAdmin(data,function(Admin){
						/*出页面*/
					app.objs.adminManageV.data=Admin;
					app.objs.adminManageV.render();
						});
					}
		},
	/*公告管理*/
	"announcementManage":{
						type:2,
						fn:function(data){
						/*获取公告*/
						app.apis.getannouncement(data,function(announcement){
							/*出页面*/
						app.objs.announcementManageV.data=announcement
						app.objs.announcementManageV.render()
							})
						}
		},
	/*客户管理*/
	"clientManage":{
					type:2,
					fn:function(data){
					/*获取客户资料*/
					app.apis.getClient(data,function(Client){
						/*出页面*/
						app.objs.clientManageV.data=Client;
						app.objs.clientManageV.render();
						})
					}
		},
	/*客户详情*/
	"clientDetail":{
				type:2,
				fn:function(data){
				/*出页面*/
				app.objs.clientDetailV.render();
				}
		},
	/*商品管理*/
	"procedureManage":{
					type:2,
					fn:function(data){
					/*获取商品信息*/
					app.apis.getProduct(data,function(Product){
						/*出页面*/
					app.objs.procedureManageV.data=Product;
					app.objs.procedureManageV.render();
						})
					}
		},
	/*招聘管理*/
	"recruitManage":{
		type:2,
		fn:function(data){
		/*获取招聘信息*/
		app.apis.getrecruit(data,function(recruit){
			/*出页面*/
			app.objs.recruitManageV.data=recruit;
			app.objs.recruitManageV.render();
			})
		}
	},
	/*公司资料管理*/
	"companyManage":{
		type:2,
		fn:function(data){
		/*获取公司资料*/
		app.apis.getcompany(data,function(company){
			/*出页面*/
			app.objs.recruitManageV.data=company;
			app.objs.recruitManageV.render();
			})	
		}
		},
	/*宣传管理*/
	"promotionManage":{
		type:2,
		fn:function(data){
		/*获取宣传信息*/
		app.apis.getpromotion(data,function(promotion){
			/*出页面*/
			app.objs.promotionManageV.data(promotion)
			app.objs.promotionManageV.render();
			})
		}
		},
	/*红包管理*/
	"redPacketManage":{
				type:2,
				fn:function(data){
				/*获取红包信息*/
				app.apis.getRedPacket(data,function(redPacket){
					/*出页面*/
					app.objs.redPacketManageV.data=redPacket;
					app.objs.redPacketManageV.render();
					})
				}
		}		
	}
app.routers=Backbone.Router.extend({
	"routes":{
		"*action":"changePage"
    },
	"changePage":function(){
		var get=$_GET();
		if(!get.page){
			get.page = "index"
			}
			app.objs.headV.type = app.objs.routeTable[get.page].type;
			if(app.objs.headV.typeBefore!=app.objs.headV.type){
				app.objs.headV.typeBefore=app.objs.headV.type;
				app.objs.headV.render();
				}
			app.objs.middleV.type = app.objs.routeTable[get.page].type;
			if(app.objs.middleV.typeBefore!=app.objs.middleV.type){
				app.objs.middleV.typeBefore=app.objs.middleV.type;
				app.objs.middleV.render();
				}
		if(!app.objs.footV.done){
			app.objs.footV.done = true;
			app.objs.footV.render();
			}
		
		app.objs.routeTable[get.page].fn(get);
		}
	});